In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
df = pd.read_csv('AI_Usage_and_Impact_on_Students_and_Professionals.csv')

In [12]:
df.head()

,User_ID,Age,Gender,Country,User_Type,Education_Level,Profession,Monthly_Income,AI_Tool,AI_Purpose,AI_Usage_Hours_Per_Day,Tasks_Performed,Monthly_AI_Cost,Productivity_Score,Accuracy_Rating,Satisfaction_Score,Time_Saved_Hours_Per_Week,Work_or_Study_Hours_Per_Day,Would_Recommend
0,U0269,30,Male,United Kingdom,Professional,Master's,Business Analyst,5421,ChatGPT,Office Work,2 hrs,Data analysis using AI-powered analytics tools...,NaN,5.3,4.0,7.0,3.9,7.3,Yes
1,U0217,30,Male,United States,Professional,Bachelor's,Customer Support Specialist,8903,ChatGPT,Customer Support,5.7,Resolving customer inquiries using AI chatbot ...,0,9.9,3.0,9.0,11.4,8.4 hrs,Yes
2,U0152,17,Male,Canada,Student,NaN,Computer Science Student,402,Chat GPT,Coding,1 hrs,NaN,20,3.2,2.0,4.0,5.2,6.7,No
3,U0264,35,FEMALE,Brazil,Professional,Bachelor's,Desenvolvedora de Software / Software Developer,1367,Meta AI,Coding,1.7,"Usar GitHub Copilot para autocompletar código,...",20,5.6,4.0,5.0,6.4,9.6,Maybe
4,U0263,19,Female,Canada,Student,Undergraduate,Biology Student,438,Perplexity AI,NaN,4.1,Using AI to generate study summaries for exam ...,0,4.7,4.0,7.0,9.2,6.2,Yes

In [13]:
df.head()

,User_ID,Age,Gender,Country,User_Type,Education_Level,Profession,Monthly_Income,AI_Tool,AI_Purpose,AI_Usage_Hours_Per_Day,Tasks_Performed,Monthly_AI_Cost,Productivity_Score,Accuracy_Rating,Satisfaction_Score,Time_Saved_Hours_Per_Week,Work_or_Study_Hours_Per_Day,Would_Recommend
0,U0269,30,Male,United Kingdom,Professional,Master's,Business Analyst,5421,ChatGPT,Office Work,2 hrs,Data analysis using AI-powered analytics tools...,NaN,5.3,4.0,7.0,3.9,7.3,Yes
1,U0217,30,Male,United States,Professional,Bachelor's,Customer Support Specialist,8903,ChatGPT,Customer Support,5.7,Resolving customer inquiries using AI chatbot ...,0,9.9,3.0,9.0,11.4,8.4 hrs,Yes
2,U0152,17,Male,Canada,Student,NaN,Computer Science Student,402,Chat GPT,Coding,1 hrs,NaN,20,3.2,2.0,4.0,5.2,6.7,No
3,U0264,35,FEMALE,Brazil,Professional,Bachelor's,Desenvolvedora de Software / Software Developer,1367,Meta AI,Coding,1.7,"Usar GitHub Copilot para autocompletar código,...",20,5.6,4.0,5.0,6.4,9.6,Maybe
4,U0263,19,Female,Canada,Student,Undergraduate,Biology Student,438,Perplexity AI,NaN,4.1,Using AI to generate study summaries for exam ...,0,4.7,4.0,7.0,9.2,6.2,Yes

In [3]:
df.drop('User_ID', axis = 1, inplace = True)

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 18 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Age                          300 non-null    object
 1   Gender                       290 non-null    object
 2   Country                      290 non-null    object
 3   User_Type                    300 non-null    object
 4   Education_Level              287 non-null    object
 5   Profession                   285 non-null    object
 6   Monthly_Income               290 non-null    object
 7   AI_Tool                      289 non-null    object
 8   AI_Purpose                   287 non-null    object
 9   AI_Usage_Hours_Per_Day       293 non-null    object
 10  Tasks_Performed              282 non-null    object
 11  Monthly_AI_Cost              288 non-null    object
 12  Productivity_Score           284 non-null    float64
 13  Accuracy_Rating              285 non-null    float64
 14  Satisfaction_Score           293 non-null    float64
 15  Time_Saved_Hours_Per_Week    290 non-null    object
 16  Work_or_Study_Hours_Per_Day  291 non-null    object
 17  Would_Recommend              295 non-null    object
dtypes: float64(3), object(15)
memory usage: 42.3+ KB

In [4]:
df['Age'] = df['Age'].fillna(df['Age'].mode()[0])

In [5]:
df['Age'].unique()

array(['30', '17', '35', '19', '32', '16', '40', '36', '22', '21', '28',
       '16 yrs', '23', '61', '24', '29', '23 yrs', '44', '18', '45', '43',
       '20', '34', '26', '33', '31', '21 yrs', '47 yrs', '37', '39', '25',
       '46', '25 yrs', '97', '54', '47', '30 yrs', '28 yrs', '27', '56',
       '63', '41', '58', '49', '55', '39 yrs', '48', '17 yrs', '53', '64',
       '38', '36 yrs'], dtype=object)

In [6]:
df['Age'] =df['Age'].str.split(' ').str[0]

In [7]:
df['Age'] = df['Age'].astype(int)

In [8]:
df['Gender'].unique()

array(['Male', 'FEMALE', 'Female', nan, 'male', 'M', 'F', 'other',
       'Other', 'female', 'MALE', 'Non-binary'], dtype=object)

In [9]:
df['Gender'] = df['Gender'].map({'Male':0, 'FEMALE':1, 'Female':1, 'nan':2, 'male':0, 'M':0, 'F':1, 'other':2,
       'Other':2, 'female':1, 'MALE':0, 'Non-binary':2})

In [10]:
df['Gender'] = df['Gender'].fillna(2)

In [11]:
df['Gender'] = df['Gender'].astype(int)

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 18 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Age                          300 non-null    int64
 1   Gender                       300 non-null    int64
 2   Country                      290 non-null    object
 3   User_Type                    300 non-null    object
 4   Education_Level              287 non-null    object
 5   Profession                   285 non-null    object
 6   Monthly_Income               290 non-null    object
 7   AI_Tool                      289 non-null    object
 8   AI_Purpose                   287 non-null    object
 9   AI_Usage_Hours_Per_Day       293 non-null    object
 10  Tasks_Performed              282 non-null    object
 11  Monthly_AI_Cost              288 non-null    object
 12  Productivity_Score           284 non-null    float64
 13  Accuracy_Rating              285 non-null    float64
 14  Satisfaction_Score           293 non-null    float64
 15  Time_Saved_Hours_Per_Week    290 non-null    object
 16  Work_or_Study_Hours_Per_Day  291 non-null    object
 17  Would_Recommend              295 non-null    object
dtypes: float64(3), int64(2), object(13)
memory usage: 42.3+ KB

In [13]:
df['Monthly_Income']= df['Monthly_Income'].str.replace('$','')

In [14]:
df['Monthly_Income']= df['Monthly_Income'].str.replace(',','')

In [15]:
df['Monthly_Income'] = df['Monthly_Income'].fillna(df['Monthly_Income'].mode()[0])

In [16]:
df['Monthly_Income'] = df['Monthly_Income'].astype(int)

In [17]:
df['Time_Saved_Hours_Per_Week'] = df['Time_Saved_Hours_Per_Week'].fillna(df['Time_Saved_Hours_Per_Week'].mode()[0])

In [18]:
df['Time_Saved_Hours_Per_Week'] = df['Time_Saved_Hours_Per_Week'].str.replace('hrs','')

In [19]:
df['Time_Saved_Hours_Per_Week'] = df['Time_Saved_Hours_Per_Week'].astype(float)

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 18 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Age                          300 non-null    int64
 1   Gender                       300 non-null    int64
 2   Country                      290 non-null    object
 3   User_Type                    300 non-null    object
 4   Education_Level              287 non-null    object
 5   Profession                   285 non-null    object
 6   Monthly_Income               300 non-null    int64
 7   AI_Tool                      289 non-null    object
 8   AI_Purpose                   287 non-null    object
 9   AI_Usage_Hours_Per_Day       293 non-null    object
 10  Tasks_Performed              282 non-null    object
 11  Monthly_AI_Cost              288 non-null    object
 12  Productivity_Score           284 non-null    float64
 13  Accuracy_Rating              285 non-null    float64
 14  Satisfaction_Score           293 non-null    float64
 15  Time_Saved_Hours_Per_Week    300 non-null    float64
 16  Work_or_Study_Hours_Per_Day  291 non-null    object
 17  Would_Recommend              295 non-null    object
dtypes: float64(4), int64(3), object(11)
memory usage: 42.3+ KB

In [21]:
df['AI_Usage_Hours_Per_Day'].unique()

array(['2 hrs', '5.7', '1 hrs', '1.7', '4.1', '1.5', '1.2', '2',
       '1.6 hrs', '2.7', '5', '0.8', '5.8', '3.9', '7.1', '9.6', '23',
       '0.9', '1.7 hrs', '1', '2.6', '1.6', '0.6', '0.7', '7.4', '5.4',
       '5.2', '3.7', '2.3', '1.9', '5.5', '5.1', '2.4', '9.1', '8', nan,
       '7.7', '1.3', '2.2 hrs', '4.6', '1.4', '7.2', '3.4', '0.5', '3.5',
       '0.7 hrs', '4.9', '4.3', '2.1', '7', '9.9 hrs', '4.8 hrs', '3.8',
       '3.6', '8.5', '2.2', '6', '1.3 hrs', '5 hrs', '1.4 hrs', '1.8',
       '3.3', '4', '3', '6.5', '2.9', '9.5', '9.7', '2.8', '3.2', '5.9',
       '1.1', '0.6 hrs', '2.5', '4.4', '9.8', '6.1', '0.9 hrs', '0.8 hrs',
       '3.1', '5.3', '6.8', '4.5', '4.2', '6.3', '8.1', '3.9 hrs',
       '4.9 hrs', '8.6', '7.9'], dtype=object)

In [22]:
df['AI_Usage_Hours_Per_Day'] = df['AI_Usage_Hours_Per_Day'].fillna(df['AI_Usage_Hours_Per_Day'].mode()[0])

In [23]:
df['AI_Usage_Hours_Per_Day'] = df['AI_Usage_Hours_Per_Day'].str.replace('hrs','')

In [24]:
df['AI_Usage_Hours_Per_Day'] = df['AI_Usage_Hours_Per_Day'].astype(float)

In [25]:
df['Monthly_AI_Cost'].unique()

array([nan, '0', '20', '30', '10', '$0 ', '50', '$30 ', '25', '$25 ',
       '$50 ', '100', '$20 '], dtype=object)

In [26]:
df['Monthly_AI_Cost']= df['Monthly_AI_Cost'].str.replace('$','')

In [27]:
df['Monthly_AI_Cost'] = df['Monthly_AI_Cost'].fillna(df['Monthly_AI_Cost'].mode()[0])

In [28]:
df['Monthly_AI_Cost'] = df['Monthly_AI_Cost'].astype(int)

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 18 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Age                          300 non-null    int64
 1   Gender                       300 non-null    int64
 2   Country                      290 non-null    object
 3   User_Type                    300 non-null    object
 4   Education_Level              287 non-null    object
 5   Profession                   285 non-null    object
 6   Monthly_Income               300 non-null    int64
 7   AI_Tool                      289 non-null    object
 8   AI_Purpose                   287 non-null    object
 9   AI_Usage_Hours_Per_Day       300 non-null    float64
 10  Tasks_Performed              282 non-null    object
 11  Monthly_AI_Cost              300 non-null    int64
 12  Productivity_Score           284 non-null    float64
 13  Accuracy_Rating              285 non-null    float64
 14  Satisfaction_Score           293 non-null    float64
 15  Time_Saved_Hours_Per_Week    300 non-null    float64
 16  Work_or_Study_Hours_Per_Day  291 non-null    object
 17  Would_Recommend              295 non-null    object
dtypes: float64(5), int64(4), object(9)
memory usage: 42.3+ KB

In [30]:
df['Work_or_Study_Hours_Per_Day'].unique()

array(['7.3', '8.4 hrs', '6.7', '9.6', '6.2', '7.4', '6.4', '3.8', '9.4',
       '8.7', '5.6', '8', '4.8', '7.6 hrs', '3', '3.9', '5.2', '9.5',
       '5.4', '7.2', '7.8', '6.5', '8.1', '6.8', '7', '6.9', '7.7', '4.1',
       '3.2', '7.5', '10.1', '12', '8.6', '7.9', '11.6', '10.7', '5.7',
       '8.8', '11', nan, '6.1', '7.6', '6.3', '10.2', '6.6', '4.5 hrs',
       '9.3', '5.9', '5.8', '9.2', '8.5', '8.7 hrs', '10.5', '2.1', '9.9',
       '11.2', '8.4', '8.3', '9.7', '11.3', '5.1', '9.1', '12.4', '4.6',
       '5.3', '7.1', '4.7', '4.9', '3.7', '9.8', '5.5', '2.3', '8.9',
       '20', '4.5', '9', '6', '7.4 hrs', '10.4', '10', '5.4 hrs', '4.4',
       '4.3', '10.3', '5.8 hrs', '7.9 hrs', '6.5 hrs', '8 hrs', '8.2',
       '2.6', '2.8', '5.9 hrs', '12.2', '10.9'], dtype=object)

In [31]:
df['Work_or_Study_Hours_Per_Day'] = df['Work_or_Study_Hours_Per_Day'].fillna(df['Work_or_Study_Hours_Per_Day'].mode()[0])
df['Work_or_Study_Hours_Per_Day'] = df['Work_or_Study_Hours_Per_Day'].str.replace('hrs','')
df['Work_or_Study_Hours_Per_Day'] = df['Work_or_Study_Hours_Per_Day'].astype(float)

In [32]:
df['Education_Level'].unique()

array(["Master's", "Bachelor's", nan, 'Undergraduate', 'High School',
       'Diploma', 'high school', 'PhD', 'BA/BSc', 'MA/MSc', 'Ph.D.',
       'Masters', "master's degree", "bachelor's degree", 'undergrad',
       'Bachelors', 'HS'], dtype=object)

In [33]:
df['Education_Level'] = df['Education_Level'].astype('string').str.strip().str.lower()

df['Education_Level'] = df['Education_Level'].replace({
    "master's": "Master's",
    "masters": "Master's",
    "master's degree": "Master's",
    "ma/msc": "Master's",

    "bachelor's": "Bachelor's",
    "bachelors": "Bachelor's",
    "bachelor's degree": "Bachelor's",
    "ba/bsc": "Bachelor's",

    "high school": "High School",
    "hs": "High School",

    "undergraduate": "Undergraduate",
    "undergrad": "Undergraduate",

    "phd": "PhD",
    "ph.d.": "PhD",

    "diploma": "Diploma"
})

In [34]:
df['Education_Level'] = df['Education_Level'].fillna('Unknown')

In [35]:
education_map = {
    'High School': 0,
    'Diploma': 1,
    'Undergraduate': 2,
    "Bachelor's": 3,
    "Master's": 4,
    'PhD': 5,
    'Unknown': -1
}

df['Education_Level_Encoded'] = df['Education_Level'].map(education_map)

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 19 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Age                          300 non-null    int64
 1   Gender                       300 non-null    int64
 2   Country                      290 non-null    object
 3   User_Type                    300 non-null    object
 4   Education_Level              300 non-null    string
 5   Profession                   285 non-null    object
 6   Monthly_Income               300 non-null    int64
 7   AI_Tool                      289 non-null    object
 8   AI_Purpose                   287 non-null    object
 9   AI_Usage_Hours_Per_Day       300 non-null    float64
 10  Tasks_Performed              282 non-null    object
 11  Monthly_AI_Cost              300 non-null    int64
 12  Productivity_Score           284 non-null    float64
 13  Accuracy_Rating              285 non-null    float64
 14  Satisfaction_Score           293 non-null    float64
 15  Time_Saved_Hours_Per_Week    300 non-null    float64
 16  Work_or_Study_Hours_Per_Day  300 non-null    float64
 17  Would_Recommend              295 non-null    object
 18  Education_Level_Encoded      300 non-null    int64
dtypes: float64(6), int64(5), object(7), string(1)
memory usage: 44.7+ KB

In [37]:
df.drop('Education_Level', axis = 1, inplace = True)

In [38]:
df['User_Type'].unique()

array(['Professional', 'Student'], dtype=object)

In [39]:
df['User_Type'] = df['User_Type'].map({
    'Student': 0,
    'Professional': 1
})

In [40]:
df['Country'].unique()

array(['United Kingdom', 'United States', 'Canada', 'Brazil', 'france',
       'Philippines', 'india', 'Pakistan', 'Australia', 'canada', 'India',
       'Kenya', 'Nigeria', 'Germany', nan, 'France', 'brazil', 'U.K.',
       'United States of America', 'philippines', 'australia'],
      dtype=object)

In [41]:
df['Country'] = df['Country'].astype('string').str.strip().str.lower()

df['Country'] = df['Country'].replace({
    'uk': 'United Kingdom',
    'u.k.': 'United Kingdom',
    'united kingdom': 'United Kingdom',

    'united states': 'United States',
    'united states of america': 'United States',

    'india': 'India',
    'canada': 'Canada',
    'france': 'France',
    'brazil': 'Brazil',
    'philippines': 'Philippines',
    'australia': 'Australia',
    'pakistan': 'Pakistan',
    'kenya': 'Kenya',
    'nigeria': 'Nigeria',
    'germany': 'Germany'
})

In [42]:
df['Country'] = df['Country'].fillna('Unknown')

In [43]:
df = pd.get_dummies(
    df,
    columns=['Country'],
    drop_first=True,
    dtype=int
)

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 29 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Age                          300 non-null    int64
 1   Gender                       300 non-null    int64
 2   User_Type                    300 non-null    int64
 3   Profession                   285 non-null    object
 4   Monthly_Income               300 non-null    int64
 5   AI_Tool                      289 non-null    object
 6   AI_Purpose                   287 non-null    object
 7   AI_Usage_Hours_Per_Day       300 non-null    float64
 8   Tasks_Performed              282 non-null    object
 9   Monthly_AI_Cost              300 non-null    int64
 10  Productivity_Score           284 non-null    float64
 11  Accuracy_Rating              285 non-null    float64
 12  Satisfaction_Score           293 non-null    float64
 13  Time_Saved_Hours_Per_Week    300 non-null    float64
 14  Work_or_Study_Hours_Per_Day  300 non-null    float64
 15  Would_Recommend              295 non-null    object
 16  Education_Level_Encoded      300 non-null    int64
 17  Country_Brazil               300 non-null    int64
 18  Country_Canada               300 non-null    int64
 19  Country_France               300 non-null    int64
 20  Country_Germany              300 non-null    int64
 21  Country_India                300 non-null    int64
 22  Country_Kenya                300 non-null    int64
 23  Country_Nigeria              300 non-null    int64
 24  Country_Pakistan             300 non-null    int64
 25  Country_Philippines          300 non-null    int64
 26  Country_United Kingdom       300 non-null    int64
 27  Country_United States        300 non-null    int64
 28  Country_Unknown              300 non-null    int64
dtypes: float64(6), int64(18), object(5)
memory usage: 68.1+ KB

In [45]:
df['Profession'].unique()

array(['Business Analyst', 'Customer Support Specialist',
       'Computer Science Student',
       'Desenvolvedora de Software / Software Developer',
       'Biology Student', 'Business Analytics Student',
       'Développeur Full Stack', 'Social Media Content Creator',
       'Digital Media Production Student', nan, 'Research Analyst',
       'Mechanical Engineering Student', 'Software Developer',
       'Software Engineering Student', 'Data Analyst',
       'Customer Service Representative', 'English Literature Student',
       'Research Technician', 'AI-Powered Customer Support Executive',
       'Kundenservice-Spezialistin / Customer Service Specialist',
       'Digital Content Creator', 'Pesquisador de Mercado',
       'Business Administration Student', 'Research Assistant',
       'Engineering Student', 'Information Technology Student',
       'Senior Software Engineer', 'Data Analytics Manager',
       'Engenheiro de Software Sênior / Tech Lead', 'Content Writer',
       'Senior Software Engineer / Technical Lead',
       'Research Scientist/Senior Research Officer',
       'Artificial Intelligence and Machine Learning Student',
       'Content Strategy Manager',
       'Social Media Content Creator / Digital Marketer',
       'Responsable de Contenu Digital',
       'Marketing Communications Officer', 'Digital Media Student',
       'Content Marketing Manager', 'Business Intelligence Analyst',
       'Desenvolvedor de Software Sênior',
       'Digital Media and Communications Student',
       'Bioinformatics Student', 'Administrative Assistant',
       'Biotechnology Student',
       'Senior Software Engineer / AI Solutions Architect',
       'Environmental Science Student',
       'Senior Software Developer / Softwareentwicklerin',
       'Customer Support Manager', 'Data Entry Specialist',
       'Data Entry Operator', 'Artificial Intelligence Research Student',
       'Digital Content Strategist', 'Molecular Biology Student',
       'Senior Content Strategist', 'Senior Machine Learning Engineer',
       'Senior Data Scientist', 'Content Strategist & Technical Writer',
       'Electronics Engineering Student', 'Junior Software Developer',
       'German Literature Student', 'Machine Learning Research Student',
       'Software Development Student', 'Senior Software Developer',
       'Mathematics Student', 'AI Customer Support Specialist',
       'Especialista em Atendimento ao Cliente com IA', 'History Student',
       'Customer Experience Manager', 'Administrative Executive',
       'Data Science Student',
       'Customer Support Specialist / AI Support Operations Manager',
       'Desenvolvedora de Sistemas Júnior', 'Digital Marketing Student',
       'Machine Learning Student', 'Content Manager',
       'AI Customer Success Manager', 'Gerente de Atendimento ao Cliente',
       'Creative Writing Student', 'Computer Science PhD Student',
       'Senior Research Scientist',
       'Content Creator/Gestor de Conteúdo Digital',
       'Junior Web Developer', 'Kundenbetreuerin mit KI-Unterstützung',
       'Pesquisador Sênior em Inteligência Artificial e Ciência de Dados',
       'Technical Writer', 'Theoretical Physics Student',
       'Biomedical Science Student', 'Physics Student',
       'Artificial Intelligence & Digital Media Student',
       'German Literature and Comparative Studies Student',
       'Analista de Dados Sênior',
       'Digital Media & Film Production Student', 'AI Content Strategist',
       'Softwareentwicklerin (Software Developer)',
       'Digital Content Creator / Social Media Manager',
       'Biomedical Engineering Student', 'Psychology Student',
       'Datenanalyst', 'Biotechnology PhD Student',
       'Développeur Logiciel (Software Developer)',
       'Electronics and Communication Engineering Student',
       'Développeur Full Stack Junior',
       'Senior Software Engineer / AI Systems Developer',
       'Research Scientist / Data Analyst', 'Content Strategist',
       'Software Developer (Diploma Qualified)',
       'Desenvolvedor de Sistemas Junior',
       'Data Analyst / Business Intelligence Specialist',
       'Assistente Administrativo', 'Digital Marketing Manager',
       'Psychology Research Student', 'Digital Content Writer',
       'Statistics Student', 'Literature Student',
       'Customer Service Executive', 'Customer Support Executive',
       'Softwareentwickler (Software Developer)',
       'Projektmanagerin (Project Manager)',
       'Software Support Technician', 'Desenvolvedora de Software',
       'Analyste de Données / Data Analyst', 'Research Scientist',
       'Academic Research Professor and Technical Writer',
       'Analista de Dados', 'Multimedia Content Producer',
       'Desenvolvedor de Sistemas (Systems Developer)'], dtype=object)

In [46]:
df['Profession'] = (
    df['Profession']
    .astype('string')
    .str.strip()
    .str.lower()
)

In [47]:
# rather than doing the one hot which creates large values and some unessary obervations, so we categroies them
# Group professions into broader categories
def categorize_profession(x):
    if pd.isna(x):
        return 'Unknown'

    if any(word in x for word in [
        'software', 'full stack', 'web developer',
        'systems developer', 'softwareentwickler',
        'développeur', 'desenvolvedor'
    ]):
        return 'Software/IT'

    if any(word in x for word in [
        'data analyst', 'data analytics', 'data scientist',
        'business intelligence', 'datenanalyst',
        'analyste de données', 'analista de dados'
    ]):
        return 'Data/Analytics'

    if any(word in x for word in [
        'machine learning', 'artificial intelligence',
        'ai ', 'ai-powered', 'ai customer',
        'artificial intelligence research'
    ]):
        return 'AI/ML'

    if any(word in x for word in [
        'research', 'scientist', 'researcher',
        'research assistant', 'research technician'
    ]):
        return 'Research'

    if any(word in x for word in [
        'content', 'social media', 'digital media',
        'marketing', 'technical writer',
        'creative writing'
    ]):
        return 'Marketing/Content'

    if any(word in x for word in [
        'customer support', 'customer service',
        'customer experience', 'customer success',
        'kundenservice', 'atendimento ao cliente'
    ]):
        return 'Customer Support'

    if 'business analyst' in x or 'business administration' in x:
        return 'Business'

    if any(word in x for word in [
        'engineering', 'engineer',
        'mechanical', 'electronics',
        'biomedical', 'biotechnology'
    ]):
        return 'Engineering'

    if 'student' in x:
        return 'Student'

    if any(word in x for word in [
        'administrative', 'administration', 'assistente administrativo'
    ]):
        return 'Administration'

    return 'Other'

In [48]:
def get_seniority(x):
    if pd.isna(x):
        return 'Unknown'

    if 'senior' in x or 'sênior' in x:
        return 'Senior'

    if 'junior' in x or 'júnior' in x:
        return 'Junior'

    if 'manager' in x or 'gerente' in x:
        return 'Manager'

    if 'lead' in x:
        return 'Lead'

    if 'executive' in x:
        return 'Executive'

    return 'Other'

In [49]:
df['Profession'].unique()

<StringArray>
[                                'business analyst',
                      'customer support specialist',
                         'computer science student',
  'desenvolvedora de software / software developer',
                                  'biology student',
                       'business analytics student',
                           'développeur full stack',
                     'social media content creator',
                 'digital media production student',
                                               <NA>,
 ...
          'softwareentwickler (software developer)',
               'projektmanagerin (project manager)',
                      'software support technician',
                       'desenvolvedora de software',
               'analyste de données / data analyst',
                               'research scientist',
 'academic research professor and technical writer',
                                'analista de dados',
                      'multimedia content producer',
    'desenvolvedor de sistemas (systems developer)']
Length: 127, dtype: string

In [50]:
df['Profession_Category'] = df['Profession'].apply(categorize_profession)

In [51]:
df['Profession_Category'].value_counts()

Profession_Category
Student              90
Software/IT          48
Marketing/Content    46
Engineering          22
Customer Support     16
Unknown              15
Data/Analytics       15
Research             13
AI/ML                13
Business              9
Other                 7
Administration        6
Name: count, dtype: int64

In [52]:
df = pd.get_dummies(
    df,
    columns=['Profession_Category'],
    drop_first=True,
    dtype=int
)

In [53]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 40 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   Age                                    300 non-null    int64
 1   Gender                                 300 non-null    int64
 2   User_Type                              300 non-null    int64
 3   Profession                             285 non-null    string
 4   Monthly_Income                         300 non-null    int64
 5   AI_Tool                                289 non-null    object
 6   AI_Purpose                             287 non-null    object
 7   AI_Usage_Hours_Per_Day                 300 non-null    float64
 8   Tasks_Performed                        282 non-null    object
 9   Monthly_AI_Cost                        300 non-null    int64
 10  Productivity_Score                     284 non-null    float64
 11  Accuracy_Rating                        285 non-null    float64
 12  Satisfaction_Score                     293 non-null    float64
 13  Time_Saved_Hours_Per_Week              300 non-null    float64
 14  Work_or_Study_Hours_Per_Day            300 non-null    float64
 15  Would_Recommend                        295 non-null    object
 16  Education_Level_Encoded                300 non-null    int64
 17  Country_Brazil                         300 non-null    int64
 18  Country_Canada                         300 non-null    int64
 19  Country_France                         300 non-null    int64
 20  Country_Germany                        300 non-null    int64
 21  Country_India                          300 non-null    int64
 22  Country_Kenya                          300 non-null    int64
 23  Country_Nigeria                        300 non-null    int64
 24  Country_Pakistan                       300 non-null    int64
 25  Country_Philippines                    300 non-null    int64
 26  Country_United Kingdom                 300 non-null    int64
 27  Country_United States                  300 non-null    int64
 28  Country_Unknown                        300 non-null    int64
 29  Profession_Category_Administration     300 non-null    int64
 30  Profession_Category_Business           300 non-null    int64
 31  Profession_Category_Customer Support   300 non-null    int64
 32  Profession_Category_Data/Analytics     300 non-null    int64
 33  Profession_Category_Engineering        300 non-null    int64
 34  Profession_Category_Marketing/Content  300 non-null    int64
 35  Profession_Category_Other              300 non-null    int64
 36  Profession_Category_Research           300 non-null    int64
 37  Profession_Category_Software/IT        300 non-null    int64
 38  Profession_Category_Student            300 non-null    int64
 39  Profession_Category_Unknown            300 non-null    int64
dtypes: float64(6), int64(29), object(4), string(1)
memory usage: 93.9+ KB

In [54]:
df.drop('Profession', axis = 1, inplace = True)

In [55]:
df['AI_Tool'].unique()

array(['ChatGPT', 'Chat GPT', 'Meta AI', 'Perplexity AI', 'Claude',
       'chatgpt', 'Microsoft Copilot', 'Google Gemini', 'Grammarly',
       'DeepSeek', nan, 'Gemini', 'Chatgpt', 'gemini', 'Copilot',
       'claude', 'copilot'], dtype=object)

In [56]:
df['AI_Tool'] = df['AI_Tool'].astype('string').str.strip().str.lower()
df['AI_Tool'] = df['AI_Tool'].replace({'ChatGPT':'chatgpt',
                                       'Chat GPT':'chatgpt',
                                       'Meta AI':'meta',
                                       'Perplexity AI':'perplexity',
                                       'Claude':'claude',
                                        'chatgpt':'chatgpt',
                                       'Microsoft Copilot':'copilot',
                                       'Google Gemini':'gemini',
                                       'Grammarly':'grammarly',
       'DeepSeek':'deepseek',
                                       'nan':'Unknow',
                                       'Gemini':'gemini',
                                       'Chatgpt':'chatgpt', 
                                       'gemini':'gemini', 
                                       'Copilot':'copilot',
       'claude':'claude',
                                       'copilot':'copilot'
    
})
df['AI_Tool'] = df['AI_Tool'].fillna('Unknow')

In [57]:
df['AI_Tool'] = (
    df['AI_Tool']
    .astype('string')
    .str.strip()
    .str.lower()
)

df['AI_Tool'] = df['AI_Tool'].replace({
    'chat gpt': 'chatgpt',
    'meta ai': 'meta',
    'perplexity ai': 'perplexity',
    'microsoft copilot': 'copilot',
    'google gemini': 'gemini',
    'nan': 'unknown'
})

df['AI_Tool'] = df['AI_Tool'].fillna('unknown')

In [58]:
df['AI_Tool'].value_counts()

AI_Tool
chatgpt       122
gemini         41
copilot        36
claude         31
perplexity     25
grammarly      14
unknow         11
meta           10
deepseek       10
Name: count, dtype: Int64

In [59]:
df = pd.get_dummies(
    df,
    columns=['AI_Tool'],
    drop_first=True,
    dtype=int
)

In [60]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 46 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   Age                                    300 non-null    int64
 1   Gender                                 300 non-null    int64
 2   User_Type                              300 non-null    int64
 3   Monthly_Income                         300 non-null    int64
 4   AI_Purpose                             287 non-null    object
 5   AI_Usage_Hours_Per_Day                 300 non-null    float64
 6   Tasks_Performed                        282 non-null    object
 7   Monthly_AI_Cost                        300 non-null    int64
 8   Productivity_Score                     284 non-null    float64
 9   Accuracy_Rating                        285 non-null    float64
 10  Satisfaction_Score                     293 non-null    float64
 11  Time_Saved_Hours_Per_Week              300 non-null    float64
 12  Work_or_Study_Hours_Per_Day            300 non-null    float64
 13  Would_Recommend                        295 non-null    object
 14  Education_Level_Encoded                300 non-null    int64
 15  Country_Brazil                         300 non-null    int64
 16  Country_Canada                         300 non-null    int64
 17  Country_France                         300 non-null    int64
 18  Country_Germany                        300 non-null    int64
 19  Country_India                          300 non-null    int64
 20  Country_Kenya                          300 non-null    int64
 21  Country_Nigeria                        300 non-null    int64
 22  Country_Pakistan                       300 non-null    int64
 23  Country_Philippines                    300 non-null    int64
 24  Country_United Kingdom                 300 non-null    int64
 25  Country_United States                  300 non-null    int64
 26  Country_Unknown                        300 non-null    int64
 27  Profession_Category_Administration     300 non-null    int64
 28  Profession_Category_Business           300 non-null    int64
 29  Profession_Category_Customer Support   300 non-null    int64
 30  Profession_Category_Data/Analytics     300 non-null    int64
 31  Profession_Category_Engineering        300 non-null    int64
 32  Profession_Category_Marketing/Content  300 non-null    int64
 33  Profession_Category_Other              300 non-null    int64
 34  Profession_Category_Research           300 non-null    int64
 35  Profession_Category_Software/IT        300 non-null    int64
 36  Profession_Category_Student            300 non-null    int64
 37  Profession_Category_Unknown            300 non-null    int64
 38  AI_Tool_claude                         300 non-null    int64
 39  AI_Tool_copilot                        300 non-null    int64
 40  AI_Tool_deepseek                       300 non-null    int64
 41  AI_Tool_gemini                         300 non-null    int64
 42  AI_Tool_grammarly                      300 non-null    int64
 43  AI_Tool_meta                           300 non-null    int64
 44  AI_Tool_perplexity                     300 non-null    int64
 45  AI_Tool_unknow                         300 non-null    int64
dtypes: float64(6), int64(37), object(3)
memory usage: 107.9+ KB

In [61]:
df['AI_Purpose'].unique()

array(['Office Work', 'Customer Support', 'Coding', nan, 'Data Analysis',
       'Content Creation', 'Writing', 'Research', 'Studying'],
      dtype=object)

In [62]:
df['AI_Purpose'] = (
    df['AI_Purpose']
    .astype('string')
    .str.strip()
)

In [63]:
df['AI_Purpose'] = df['AI_Purpose'].fillna('Unknown')

In [64]:
df['AI_Purpose'].value_counts()

AI_Purpose
Coding              70
Writing             49
Studying            41
Research            40
Content Creation    29
Data Analysis       25
Customer Support    22
Unknown             13
Office Work         11
Name: count, dtype: Int64

In [65]:
df = pd.get_dummies(
    df,
    columns=['AI_Purpose'],
    drop_first=True,
    dtype=int
)

In [66]:
df['Would_Recommend'].unique()

array(['Yes', 'No', 'Maybe', nan], dtype=object)

In [67]:
df['Would_Recommend'] = df['Would_Recommend'].map({
    'No': 0,
    'Maybe': 1,
    'Yes': 2
})

In [68]:
df = df.dropna(subset=['Would_Recommend'])

In [69]:
df['Tasks_Performed'].unique()

array(['Data analysis using AI-powered analytics tools, automated report generation, process optimization modelling, AI-assisted business intelligence reporting',
       'Resolving customer inquiries using AI chatbot platforms, drafting personalized email responses with AI writing assistants, analyzing customer sentiment with AI tools, managing support tickets with AI-powered ticketing systems',
       nan,
       'Usar GitHub Copilot para autocompletar código, debugar aplicações com assistência de IA, otimizar algoritmos com sugestões de IA, revisar e refatorar código existente',
       'Using AI to generate study summaries for exam preparation, getting help with practice problem solutions, organizing research paper notes',
       'Statistical analysis on datasets, data visualization with Python libraries, predictive modeling for coursework, business intelligence report generation',
       'Automated code review with AI-powered linters, Generated boilerplate code and API endpoints using GitHub Copilot, Debugged complex algorithms with AI assistance, Optimized database queries using AI suggestions',
       'Creating Instagram/TikTok captions with AI writing tools, Generating YouTube thumbnails and video descriptions using AI design assistants, Editing photos and videos with AI-powered software',
       'Creating YouTube video scripts, Designing social media graphics with AI image generators, Writing blog content for tech topics',
       'Email copywriting, Social media post creation, Blog article drafting, Product description writing',
       'Literature review and synthesis using AI-powered databases, Data analysis and pattern recognition, Research paper writing and academic content generation',
       'Literature review and paper summarization, Data analysis for lab experiments, Generating research hypotheses, Technical documentation and report writing',
       'Using AI code completion tools for writing Python functions, debugging code with AI-assisted analysis, generating unit test cases with AI tools',
       'Debugging code with AI assistance, generating code snippets for assignments, learning programming concepts through AI explanations',
       'Automated data cleaning and processing with Python scripts, building predictive models using machine learning algorithms, generating interactive dashboards and visualizations in Power BI',
       'Responding to customer inquiries via AI chatbots, drafting personalized support emails using AI writing assistants, resolving common technical issues with AI-guided troubleshooting scripts',
       'Drafting research papers on literary analysis, brainstorming essay outlines, proofreading and refining academic writing, generating content summaries for thesis work',
       'Literature review for lab reports, summarizing research papers on molecular genetics, generating study notes from scientific articles',
       'Literature review synthesis using AI search tools, Data analysis and statistical reporting with AI-assisted tools, Survey data organization and preliminary findings documentation',
       'AI chatbot management and customer query routing, multilingual customer response handling using AI tools, customer complaint analysis and resolution tracking',
       'Essay structuring and outline generation, thesis statement refinement, academic paper proofreading and grammar checking, creative writing brainstorming',
       'Debugging Python code with AI assistants, generating boilerplate code for web projects, learning algorithms through AI-generated explanations',
       'Analyzing complex physics problems, generating study notes from lecture content, debugging code for coursework projects, creating visual explanations of thermodynamic concepts',
       'Generating social media captions with AI, Creating blog post drafts using language models, Editing photos and videos with AI tools, Scheduling posts across multiple platforms',
       'Writing and debugging Python code, generating documentation for projects, optimizing algorithms',
       'Análise de tendências usando ferramentas de IA, extração de dados de fontes públicas, geração de relatórios automatizados, síntese de artigos acadêmicos',
       'Using AI to generate practice exam questions, summarizing research papers, explaining complex concepts like cellular respiration',
       'Literature review and source compilation, Data analysis and statistical interpretation, Essay research and citation management',
       'Essay composition and structure planning, grammar checking and proofreading, research paper summarization, creative writing feedback and editing',
       'Literature review automation using AI databases, conducting qualitative data analysis with AI tools, generating research reports and summaries, market research data collection and synthesis',
       'Literature review using AI search tools, data analysis with AI-powered statistical software, market research report generation, academic paper summarization',
       'Solving physics problems with AI explanation, generating practice questions for exams, translating complex concepts into simplified notes',
       'Generating practice problems and solutions for thermodynamics assignments, debugging Python code for finite element analysis projects, summarizing lecture notes on fluid mechanics concepts',
       'Literature review and paper summarization, Data analysis and interpretation, Research proposal drafting, Scientific article finding and organization',
       'Code review and optimization using AI assistants, automated bug detection and debugging with AI tools, AI-assisted documentation generation, infrastructure code maintenance',
       'Building predictive models with Python and scikit-learn, Creating business intelligence dashboards in Tableau, Performing statistical analysis on customer datasets',
       'Desenvolvimento de algoritmos com assistência de IA, code review automatizado com ferramentas de IA, arquitetura de sistemas de software, mentoria de equipes em práticas de desenvolvimento com IA',
       'Code generation and debugging using AI, automated code review and optimization, rapid prototyping using AI-assisted development frameworks, API design and documentation using AI tools',
       'Code debugging and optimization using AI assistants, automated test case generation, API integration and documentation, algorithm optimization suggestions',
       'Using AI to solve physics problems, generating study summaries for calculus, translating technical documents from English to Portuguese',
       'Debugging code with AI assistants, Learning Python and JavaScript syntax, Solving LeetCode problems with AI explanations',
       'Literature review automation with AI tools, data analysis and pattern recognition, research paper synthesis and summarization, hypothesis validation using machine learning models',
       'Debugging Python code with AI-powered IDE plugins, Generating optimization algorithms for data structures, Writing and testing unit tests for complex modules',
       'Uses AI tools to generate initial content drafts, optimize SEO metadata and headlines, streamline editing and proofreading processes, manage multi-channel content calendars',
       'Essay composition and structure planning, grammar and spelling correction, brainstorming ideas for creative writing assignments',
       'Literature review and paper summarization, Data analysis for research datasets, Academic paper organization and citation management',
       'Creating engaging social media posts with AI writing tools, Generating captions and hashtags using AI, Editing and optimizing images with AI-powered design tools, Producing video content summaries and descriptions',
       "Création d'articles de blog avec assistance IA, Génération de contenu pour réseaux sociaux, Optimisation SEO avec outils IA, Édition et révision de textes",
       'Essay drafting and outline generation, academic paper research summarization, creative writing feedback and editing',
       'Debugging Python code with AI code analysis, Writing SQL queries for database projects, Generating HTML/CSS templates for web assignments',
       'AI-assisted content writing for social media and marketing campaigns, proofreading and editing copy with AI grammar tools, generating email newsletters and promotional materials',
       'Drafting customer responses using AI writing assistants, analyzing customer feedback with sentiment analysis tools, resolving FAQs using AI knowledge base systems, escalating complex issues to senior staff',
       'Using AI to solve physics and calculus problems, generating practice exam questions, translating technical documentation from English to Portuguese',
       'Creating social media graphics with AI design tools, Writing blog posts and articles with AI writing assistants, Generating video scripts and editing content with AI video tools',
       'Creating blog posts and web copy with AI writing assistants, editing and refining client proposals, generating social media content calendars and posts',
       'Statistical analysis of datasets, data visualization using Python libraries, predictive modeling with machine learning algorithms, database query optimization',
       'Cleaning and processing customer transaction data, generating sales trend reports using Python, creating data visualizations in Power BI dashboards',
       'Usar GitHub Copilot para completar código, gerar testes unitários com IA, otimizar algoritmos com sugestões de IA, revisar e debugar código com assistentes de IA',
       'AI-assisted blog writing and SEO optimization, video scriptwriting and thumbnail design generation, social media content creation and caption generation',
       'Literature review automation with AI summarization, designing research methodology frameworks, analyzing genomic datasets using machine learning models, peer review preparation assistance',
       'Writing and debugging Python code using AI assistants, automating repetitive coding tasks with AI tools, code review and optimization with AI-powered suggestions',
       'Code debugging and optimization, API development and integration, machine learning model training and implementation',
       'Debugging code with AI assistance, generating boilerplate code for projects, learning new programming concepts through AI explanations',
       'Using AI to generate study summaries, practice exam questions, and lab report writing assistance',
       'Data entry and document formatting with AI tools, scheduling meetings and managing calendar using AI assistants, generating business reports with AI summarization software, proofreading emails and correspondence using grammar AI',
       'Code generation and debugging with AI assistants, automated testing and deployment pipeline optimization, machine learning model implementation and optimization',
       'Building predictive models with machine learning algorithms, Creating automated dashboards for business intelligence, Cleaning and transforming large datasets for analysis',
       'Literature review automation, research paper summarization, data analysis and visualization, hypothesis generation',
       'Essay composition and structure planning, grammar and style checking, research paper organization, content brainstorming for creative writing assignments',
       'Running SQL queries and Python scripts to extract and clean datasets, Creating interactive dashboards and visualizations in Tableau, Performing statistical analysis and generating insights reports',
       'Code generation and optimization using AI assistants, automated testing and bug detection with AI tools, documentation generation from code comments, refactoring legacy code with AI suggestions',
       'Using AI chatbots to handle routine customer inquiries, training support staff on AI tools, monitoring AI-assisted ticket resolution quality',
       'Organizing customer datasets with Excel and Python scripts, creating automated reports using AI-powered analytics tools, cleaning and validating data quality for business intelligence dashboards',
       'Data cleaning and validation using Python scripts, Excel spreadsheet automation with AI tools, generating automated reports from raw datasets',
       'Literature review and paper summarization, debugging and optimizing machine learning code, generating research hypotheses and experiment design, analyzing complex datasets and statistical modeling',
       'AI-assisted blog writing and SEO optimization, social media caption generation, video script creation with AI tools, content calendar planning using AI analytics',
       'Code review and optimization using AI assistants, automated testing and debugging with AI tools, API development and integration, documentation generation',
       'Literature review and scientific paper analysis, data analysis and statistical interpretation, hypothesis generation and research methodology planning',
       'Generating blog content using AI writing assistants, creating social media copy with AI tools, editing and refining multimedia content with AI enhancement software, developing content calendars and briefs',
       'Code generation and debugging with AI assistants, algorithm optimization using neural networks, automated testing and code review with AI tools',
       'Building predictive models using machine learning, Processing large datasets with Python/SQL, Creating automated dashboards and reports, Performing statistical analysis on business metrics',
       'Email management and scheduling with AI tools, Document formatting and data entry using automation software, Report generation and analysis with spreadsheet AI features',
       'AI-assisted article writing and research, document translation and localization, automated report generation, editing and proofreading with AI tools',
       'Writing Python scripts with AI code completion, debugging code errors using ChatGPT, generating SQL queries for database management, refactoring JavaScript functions with AI assistance',
       'Essay structure planning, grammar and spelling correction, essay topic research, writing feedback and revision suggestions',
       'Literature review and paper summarization, Data analysis for research projects, Hypothesis generation for experiments, Academic writing and citation organization',
       'Literature review and paper summarization, Training neural networks for experimental validation, Data analysis and statistical modeling',
       'Debugging Python code with AI assistance, generating boilerplate code templates, learning JavaScript syntax through AI explanations',
       'Code review and debugging using AI assistants, automated testing script generation, documentation and comment generation, API integration optimization',
       'Using AI to explain complex concepts like cellular respiration and photosynthesis, generating practice questions for AP Biology exams, summarizing dense textbook chapters into study notes',
       'Literature review and paper summarization, Research paper analysis and concept extraction, Experimental data interpretation and analysis',
       'Drafting marketing copy with AI assistance, generating blog outlines and article summaries, editing and refining written content using AI tools, creating email campaign content',
       'Solving differential equations and linear algebra problems, generating practice exam questions and solutions, explaining complex mathematical concepts through AI-assisted tutorials',
       'Automatizar respostas de chatbot para FAQ, analisar sentimento de clientes em redes sociais, gerenciar tickets de suporte com priorização inteligente, personalizar recomendações de produtos',
       'Literature review and document summarization, Historical timeline creation and fact verification, Research paper outline generation',
       'Implementing AI chatbots for customer inquiries, analyzing customer feedback using NLP tools, managing support ticket automation with AI systems',
       'Email management and scheduling using AI, document formatting and report generation, data entry and spreadsheet organization, customer inquiry responses',
       'Generating study summaries from lecture notes, debugging Python code for machine learning assignments, explaining complex statistical concepts and algorithms',
       'Debugging code with AI assistance, Learning new programming frameworks, Writing and testing algorithms, Code optimization and refactoring',
       'Manages AI-powered chatbot responses for customer inquiries, Analyzes customer sentiment using NLP tools, Optimizes support ticket routing with machine learning algorithms, Trains and monitors AI systems for quality assurance',
       'Drafting advertising copy with AI assistance, Proofreading and editing marketing materials, Generating content ideas for campaigns using AI tools',
       'Utilizar GitHub Copilot para autocompletar código, usar ChatGPT para debugar erros em Python, aplicar IA para gerar testes automatizados',
       'AI-assisted blog writing and SEO optimization, social media caption generation, video script composition, graphic design concept ideation',
       'Blog post creation using AI writing assistants, social media caption generation, email newsletter drafting, proofreading and editing with grammar tools',
       'Respond to customer inquiries using AI chatbots, analyze sentiment in support tickets with NLP tools, draft personalized customer responses, resolve issues through AI-assisted knowledge bases',
       'Essay composition and refinement, Research paper writing and citation organization, Creative story development and editing',
       'Debugging Python code with AI pair programming, generating neural network architectures, optimizing algorithm efficiency',
       'Creating website copy and blog articles with AI writing assistants, generating social media posts and captions, editing and optimizing content for SEO',
       'Explaining complex physics concepts, Generating practice problems with solutions, Debugging MATLAB code for simulations',
       'AI-powered chatbot configuration and training, customer sentiment analysis using NLP models, automated ticket classification and routing, customer feedback analysis and reporting',
       'Implementar chatbots para respostas automáticas, supervisionar equipe de suporte via AI analytics, analisar satisfação de clientes com ferramentas de IA',
       'Essay structuring and outlining, narrative development and storytelling, grammar checking and style refinement, research paper organization',
       'AI chatbot response review and optimization, automated ticket categorization and routing, customer sentiment analysis using AI tools, knowledge base article generation',
       'Debugging code with AI assistance, generating boilerplate code for projects, learning new programming concepts through AI explanations, optimizing algorithms',
       'Generating practice problem sets, debugging Python code, summarizing research papers, creating study guides for exams',
       'Debugging code with AI assistance, generating code snippets for assignments, learning programming concepts through AI-powered tutorials',
       'Literature review automation, research paper summarization, data analysis and visualization, academic source discovery and organization',
       'Using ChatGPT to explain statistical concepts, generating practice problems with Python code examples, summarizing research papers for assignments',
       'Essay drafting and brainstorming, grammar checking and proofreading, creative writing prompt generation',
       'Debugging code with AI assistance, Generating boilerplate code and snippets, Optimizing algorithms and performance',

In [70]:
def extract_tasks(x):
    if pd.isna(x):
        return {
            'task_coding': 0,
            'task_data_analysis': 0,
            'task_research': 0,
            'task_writing': 0,
            'task_content_creation': 0,
            'task_customer_support': 0,
            'task_studying': 0,
            'task_reporting': 0
        }

    x = x.lower()

    return {
        'task_coding': int(any(word in x for word in [
            'code', 'coding', 'debug', 'programming',
            'python', 'javascript', 'sql', 'algorithm'
        ])),

        'task_data_analysis': int(any(word in x for word in [
            'data analysis', 'data analysis', 'statistical analysis',
            'data visualization', 'dataset', 'data cleaning',
            'predictive modeling', 'machine learning'
        ])),

        'task_research': int(any(word in x for word in [
            'research', 'literature review', 'research paper',
            'hypothesis', 'academic'
        ])),

        'task_writing': int(any(word in x for word in [
            'writing', 'essay', 'proofreading', 'documentation',
            'article', 'blog', 'copywriting'
        ])),

        'task_content_creation': int(any(word in x for word in [
            'social media', 'content creation', 'video',
            'youtube', 'caption', 'graphic', 'thumbnail'
        ])),

        'task_customer_support': int(any(word in x for word in [
            'customer', 'support', 'chatbot', 'ticket',
            'inquiries', 'complaint'
        ])),

        'task_studying': int(any(word in x for word in [
            'study', 'exam', 'practice questions',
            'lecture notes', 'study summaries'
        ])),

        'task_reporting': int(any(word in x for word in [
            'report', 'reporting', 'dashboard',
            'business intelligence'
        ]))
    }

In [71]:
task_features = df['Tasks_Performed'].apply(extract_tasks)

task_df = pd.DataFrame(task_features.tolist(), index=df.index)

df = pd.concat([df, task_df], axis=1)

In [72]:
df.drop('Tasks_Performed', axis=1, inplace=True)

In [73]:
df.shape

(295, 60)

In [74]:
print("Shape:", df.shape)
print("Missing values:")
print(df.isnull().sum())
print("\nData types:")
print(df.dtypes)

Shape: (295, 60)
Missing values:
Age                                       0
Gender                                    0
User_Type                                 0
Monthly_Income                            0
AI_Usage_Hours_Per_Day                    0
Monthly_AI_Cost                           0
Productivity_Score                       16
Accuracy_Rating                          15
Satisfaction_Score                        7
Time_Saved_Hours_Per_Week                 0
Work_or_Study_Hours_Per_Day               0
Would_Recommend                           0
Education_Level_Encoded                   0
Country_Brazil                            0
Country_Canada                            0
Country_France                            0
Country_Germany                           0
Country_India                             0
Country_Kenya                             0
Country_Nigeria                           0
Country_Pakistan                          0
Country_Philippines                       0
Country_United Kingdom                    0
Country_United States                     0
Country_Unknown                           0
Profession_Category_Administration        0
Profession_Category_Business              0
Profession_Category_Customer Support      0
Profession_Category_Data/Analytics        0
Profession_Category_Engineering           0
Profession_Category_Marketing/Content     0
Profession_Category_Other                 0
Profession_Category_Research              0
Profession_Category_Software/IT           0
Profession_Category_Student               0
Profession_Category_Unknown               0
AI_Tool_claude                            0
AI_Tool_copilot                           0
AI_Tool_deepseek                          0
AI_Tool_gemini                            0
AI_Tool_grammarly                         0
AI_Tool_meta                              0
AI_Tool_perplexity                        0
AI_Tool_unknow                            0
AI_Purpose_Content Creation               0
AI_Purpose_Customer Support               0
AI_Purpose_Data Analysis                  0
AI_Purpose_Office Work                    0
AI_Purpose_Research                       0
AI_Purpose_Studying                       0
AI_Purpose_Unknown                        0
AI_Purpose_Writing                        0
task_coding                               0
task_data_analysis                        0
task_research                             0
task_writing                              0
task_content_creation                     0
task_customer_support                     0
task_studying                             0
task_reporting                            0
dtype: int64

Data types:
Age                                        int64
Gender                                     int64
User_Type                                  int64
Monthly_Income                             int64
AI_Usage_Hours_Per_Day                   float64
Monthly_AI_Cost                            int64
Productivity_Score                       float64
Accuracy_Rating                          float64
Satisfaction_Score                       float64
Time_Saved_Hours_Per_Week                float64
Work_or_Study_Hours_Per_Day              float64
Would_Recommend                          float64
Education_Level_Encoded                    int64
Country_Brazil                             int64
Country_Canada                             int64
Country_France                             int64
Country_Germany                            int64
Country_India                              int64
Country_Kenya                              int64
Country_Nigeria                            int64
Country_Pakistan                           int64
Country_Philippines                        int64
Country_United Kingdom                     int64
Country_United States                      int64
Country_Unknown                            int64
Profession_Category_Administration         int64
Profession_Category_Business               int64
Profession_Category_Customer Support       int64
Profession_Category_Data/Analytics         int64
Profession_Category_Engineering            int64
Profession_Category_Marketing/Content      int64
Profession_Category_Other                  int64
Profession_Category_Research               int64
Profession_Category_Software/IT            int64
Profession_Category_Student                int64
Profession_Category_Unknown                int64
AI_Tool_claude                             int64
AI_Tool_copilot                            int64
AI_Tool_deepseek                           int64
AI_Tool_gemini                             int64
AI_Tool_grammarly                          int64
AI_Tool_meta                               int64
AI_Tool_perplexity                         int64
AI_Tool_unknow                             int64
AI_Purpose_Content Creation                int64
AI_Purpose_Customer Support                int64
AI_Purpose_Data Analysis                   int64
AI_Purpose_Office Work                     int64
AI_Purpose_Research                        int64
AI_Purpose_Studying                        int64
AI_Purpose_Unknown                         int64
AI_Purpose_Writing                         int64
task_coding                                int64
task_data_analysis                         int64
task_research                              int64
task_writing                               int64
task_content_creation                      int64
task_customer_support                      int64
task_studying                              int64
task_reporting                             int64
dtype: object

In [75]:
df['Productivity_Score']= df['Productivity_Score'].fillna(df['Productivity_Score'].mode()[0])

In [76]:
df['Productivity_Score'] = df['Productivity_Score'].astype(float)

In [77]:
df['Accuracy_Rating'] =  df['Accuracy_Rating'].fillna(df['Productivity_Score'].mode()[0])

In [78]:
df['Accuracy_Rating'] = df['Accuracy_Rating'].astype(float)

In [79]:
df['Satisfaction_Score'] =  df['Satisfaction_Score'].fillna(df['Satisfaction_Score'].mode()[0])

In [80]:
df['Satisfaction_Score'] = df['Satisfaction_Score'].astype(float)

In [92]:
from sklearn.model_selection import train_test_split

X = df.drop('Would_Recommend', axis=1)
y = df['Would_Recommend']

x_train, x_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [93]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)

model.fit(x_train, y_train)

C:\Users\udhay sai kiran\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(max_iter=1000)

In [94]:
y_pred = model.predict(x_test)

In [95]:
y_pred

array([0., 1., 2., 2., 2., 2., 2., 2., 2., 0., 2., 2., 0., 2., 2., 0., 0.,
       0., 2., 0., 0., 0., 0., 2., 2., 0., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 0., 2., 2., 0., 2., 2., 2., 2., 2., 0., 1., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2.])

In [96]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

print("Accuracy:", accuracy_score(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.6440677966101694

Classification Report:
              precision    recall  f1-score   support

         0.0       0.50      0.47      0.48        15
         1.0       0.00      0.00      0.00         9
         2.0       0.72      0.89      0.79        35

    accuracy                           0.64        59
   macro avg       0.41      0.45      0.43        59
weighted avg       0.55      0.64      0.59        59


Confusion Matrix:
[[ 7  1  7]
 [ 4  0  5]
 [ 3  1 31]]

In [97]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 295 entries, 0 to 299
Data columns (total 60 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   Age                                    295 non-null    int64
 1   Gender                                 295 non-null    int64
 2   User_Type                              295 non-null    int64
 3   Monthly_Income                         295 non-null    int64
 4   AI_Usage_Hours_Per_Day                 295 non-null    float64
 5   Monthly_AI_Cost                        295 non-null    int64
 6   Productivity_Score                     295 non-null    float64
 7   Accuracy_Rating                        295 non-null    float64
 8   Satisfaction_Score                     295 non-null    float64
 9   Time_Saved_Hours_Per_Week              295 non-null    float64
 10  Work_or_Study_Hours_Per_Day            295 non-null    float64
 11  Would_Recommend                        295 non-null    float64
 12  Education_Level_Encoded                295 non-null    int64
 13  Country_Brazil                         295 non-null    int64
 14  Country_Canada                         295 non-null    int64
 15  Country_France                         295 non-null    int64
 16  Country_Germany                        295 non-null    int64
 17  Country_India                          295 non-null    int64
 18  Country_Kenya                          295 non-null    int64
 19  Country_Nigeria                        295 non-null    int64
 20  Country_Pakistan                       295 non-null    int64
 21  Country_Philippines                    295 non-null    int64
 22  Country_United Kingdom                 295 non-null    int64
 23  Country_United States                  295 non-null    int64
 24  Country_Unknown                        295 non-null    int64
 25  Profession_Category_Administration     295 non-null    int64
 26  Profession_Category_Business           295 non-null    int64
 27  Profession_Category_Customer Support   295 non-null    int64
 28  Profession_Category_Data/Analytics     295 non-null    int64
 29  Profession_Category_Engineering        295 non-null    int64
 30  Profession_Category_Marketing/Content  295 non-null    int64
 31  Profession_Category_Other              295 non-null    int64
 32  Profession_Category_Research           295 non-null    int64
 33  Profession_Category_Software/IT        295 non-null    int64
 34  Profession_Category_Student            295 non-null    int64
 35  Profession_Category_Unknown            295 non-null    int64
 36  AI_Tool_claude                         295 non-null    int64
 37  AI_Tool_copilot                        295 non-null    int64
 38  AI_Tool_deepseek                       295 non-null    int64
 39  AI_Tool_gemini                         295 non-null    int64
 40  AI_Tool_grammarly                      295 non-null    int64
 41  AI_Tool_meta                           295 non-null    int64
 42  AI_Tool_perplexity                     295 non-null    int64
 43  AI_Tool_unknow                         295 non-null    int64
 44  AI_Purpose_Content Creation            295 non-null    int64
 45  AI_Purpose_Customer Support            295 non-null    int64
 46  AI_Purpose_Data Analysis               295 non-null    int64
 47  AI_Purpose_Office Work                 295 non-null    int64
 48  AI_Purpose_Research                    295 non-null    int64
 49  AI_Purpose_Studying                    295 non-null    int64
 50  AI_Purpose_Unknown                     295 non-null    int64
 51  AI_Purpose_Writing                     295 non-null    int64
 52  task_coding                            295 non-null    int64
 53  task_data_analysis                     295 non-null    int64
 54  task_research                          295 non-null    int64
 55  task_writing                           295 non-null    int64
 56  task_content_creation                  295 non-null    int64
 57  task_customer_support                  295 non-null    int64
 58  task_studying                          295 non-null    int64
 59  task_reporting                         295 non-null    int64
dtypes: float64(7), int64(53)
memory usage: 140.6 KB

In [100]:
# in next step we are using a better model like decision tree
from sklearn.tree import DecisionTreeClassifier

dt_model = DecisionTreeClassifier(random_state=42)

dt_model.fit(x_train, y_train)

DecisionTreeClassifier(random_state=42)

In [102]:
dt_pred = dt_model.predict(x_test)

In [104]:
dt_pred

array([0., 0., 0., 2., 1., 2., 2., 2., 2., 1., 2., 2., 0., 2., 0., 2., 0.,
       1., 0., 2., 1., 2., 2., 2., 2., 2., 1., 2., 1., 2., 1., 2., 2., 0.,
       2., 2., 1., 2., 0., 2., 2., 1., 2., 0., 0., 2., 2., 1., 2., 2., 0.,
       2., 0., 2., 2., 1., 2., 2., 2.])